#-
# ==========================================================================
# Copyright (C) 1995 - 2006 Autodesk, Inc. and/or its licensors.  All 
# rights reserved.
#
# The coded instructions, statements, computer programs, and/or related 
# material (collectively the "Data") in these files contain unpublished 
# information proprietary to Autodesk, Inc. ("Autodesk") and/or its 
# licensors, which is protected by U.S. and Canadian federal copyright 
# law and by international treaties.
#
# The Data is provided for use exclusively by You. You have the right 
# to use, modify, and incorporate this Data into other products for 
# purposes authorized by the Autodesk software license agreement, 
# without fee.
#
# The copyright notices in the Software and this entire statement, 
# including the above license grant, this restriction and the 
# following disclaimer, must be included in all copies of the 
# Software, in whole or in part, and all derivative works of 
# the Software, unless such copies or derivative works are solely 
# in the form of machine-executable object code generated by a 
# source language processor.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. 
# AUTODESK DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED 
# WARRANTIES INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF 
# NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR 
# PURPOSE, OR ARISING FROM A COURSE OF DEALING, USAGE, OR 
# TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS LICENSORS 
# BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL, 
# DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK 
# AND/OR ITS LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY 
# OR PROBABILITY OF SUCH DAMAGES.
#
# ==========================================================================
#+

# import maya
# maya.cmds.loadPlugin("helloWorldCmd.py")
# maya.cmds.spHelloWorld()

import sys
import maya.OpenMaya as OM
import maya.OpenMayaMPx as MPx

kPluginCmdName = "spHelloWorldArgs"

kNameFlag       = "-n"
kNameLongFlag   = "-name"
kAgeFlag        = "-y"
kAgeLongFlag    = "-years"

# command
class scriptedCommand(MPx.MPxCommand):
    def __init__(self):
        MPx.MPxCommand.__init__(self)

    def doIt(self,argList):
        argData = OM.MArgDatabase(self.syntax(),argList)
        nameMsg = "Hello Stranger"
        if argData.isFlagSet(kNameFlag):
            nameMsg = "Hello %s"%argData.flagArgumentString(kNameFlag, 0)
        
        ageMsg = "I dont know your age"
        if argData.isFlagSet(kAgeFlag):
            ageMsg = "You are %s years old" % int(argData.flagArgumentDouble(kAgeFlag, 0))

        print "\n",nameMsg
        print ageMsg

# Creator
def cmdCreator():
    return MPx.asMPxPtr( scriptedCommand() )
    
# Syntax creator
def syntaxCreator():
    syntax = OM.MSyntax()
    syntax.addFlag(kNameFlag, kNameLongFlag,OM.MSyntax.kString)
    syntax.addFlag(kAgeFlag, kAgeLongFlag,OM.MSyntax.kDouble)
    return syntax

# Initialize the script plug-in
def initializePlugin(mobject):
    mplugin = MPx.MFnPlugin(mobject,"TDChannel", "1.0", "Any")
    try:
        mplugin.registerCommand( kPluginCmdName, cmdCreator,syntaxCreator )
    except:
        sys.stderr.write( "Failed to register command: %s\n" % kPluginCmdName )
        raise

# Uninitialize the script plug-in
def uninitializePlugin(mobject):
    mplugin = MPx.MFnPlugin(mobject)
    try:
        mplugin.deregisterCommand( kPluginCmdName )
    except:
        sys.stderr.write( "Failed to unregister command: %s\n" % kPluginCmdName )
        raise

